rule Base64ReverseShell {
	   meta:
      description = "Detects a portion of a known malicious base64 Powershell string"
      author = "Ian Bell"
      reference = "none"
      date = "2023-05-12"
   strings:
      $x01 = "JAB3AGUAcgAgAD0AIABHAGUAdAAtAFcATQBJAE8AYgBqAGUAYwB0ACAAVwBpAG4AMwAyAF8AQwBvAG0AcAB1AHQAZQByAFMAeQBzAHQAZQBtAHwAIABTAGUAbABlAGMAdAAtAE8AYgBqAGUAYwB0ACAALQBFAHgAcABhAG4AZABQAHIAbwBwAGUAcgB0AHkAIABEAG8AbQBhAGkAbgA7AAoAIwBjAHgAeABjACAAIAAxACAAMQAgADEAIAAxACAAMQAgADEAIAAxACAAMQAgADEAIAAyACAAMgAgADIAIAAyADIAIAAyACAAMgAgADIAIAAyACAAMgAgAHAAcgBpAG4AdAAKACMAegB4AHoAeAAgADEAIAAxACAAMQAgADEAIAAxACAAMQAgADEAIAAxACAAMQAxADEAIABwAHIAaQBuAHQACgAkAGEAcgByAGEAcgAgAD0AIABAACgAJwBjAHIAbwBzAH"
	  
   condition:
      1 of ($x*)
}
