rule PaperCutBase64 {
	   meta:
      description = "Detects a portion of a known malicious base64 Powershell string"
      author = "Ian Bell"
      reference = "none"
      date = "2023-05-12"
   strings:
      $x01 = "JAB3AGUAcgAgAD0AIABHAGUAdAAtAFcATQBJAE8AYgBqAGUAYwB0ACAAVwBpAG4AMwAyAF8AQwBvAG0AcAB1AHQAZQByAFMAeQBzAHQAZQBtAHwAIABTAGUAbABlAGMAdAAtA"
      $x02 = "QALAAwACwAJABiAHkAdABlAHQAbwBvAHUAdAAuAEwAZQBuAGcAdABoACkACgAkAHMAdAByAG0AbgAuAEYAbAB1AHMAaAAoACkACgBTAHQAYQByAHQALQBTAGwAZQBlAHAAIAAtAFMAZQBjAG8AbgBkAHMAIAAxAAoAfQAKACQAcgBjAG8AbgBuAHMALgBDAGwAbwBzAGUAKAApAAoAUwB0AGEAcgB0AC0AUwBsAGUAZQBwACAALQBTAGUAYwBvAG4AZABzACAAMwAKAH0ACgA="
	  
   condition:
      1 of ($x*)
}
